New merkle tree sc
Galactica-corp/zkKYC pull request #24
Opened 2023-06-25 23:38 UTC by anhdungle93

Change current incremental merkle tree so that one can change content of each leaf, hence enables revocation

2023-06-29 14:54 UTC, zwilling requested changes
Nice implementation of the sparse merkle tree.
I added some comments on potential issues and code style.

2023-06-30 12:07 UTC, zwilling approved these changes
Only minor improvement suggestions. Do you work on them or merge it already?

2023-07-11 14:03 UTC, anhdungle93 commented on tasks/createZKKYC.ts
> +    if (!leafIndices.includes(index)) {
added a new sorting

2023-07-20 10:57 UTC, zwilling commented on tasks/reissueZKKYC.ts
> +task("createZkKYC", "Task to create a zkKYC certificate with input parameters")
I think the task name should be different from the other `createZkKYC` task.

2023-09-06 10:00 UTC, merged